# Generated by Django 5.0.1 on 2024-02-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0003_alter_kitob_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
